"""Add attachments table for image-sharing feature.

See docs/plans/2026-05-22-attachments-share-design.md.

Revision ID: 9249c3b6dab4
Revises: 325493494d90
Create Date: 2026-05-23 02:32:13.220445

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9249c3b6dab4'
down_revision: str | Sequence[str] | None = '325493494d90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=8), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('thumb_path', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('original_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploader_fingerprint', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_slug'), ['slug'], unique=True)
        batch_op.create_index(
            batch_op.f('ix_attachments_uploaded_at'),
            ['uploaded_at'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_attachments_slug'))

    op.drop_table('attachments')
    # ### end Alembic commands ###
