"""add message.pubkey_prefix

Revision ID: 93d0e18f86f7
Revises: d22e0f4f34be
Create Date: 2026-05-19 10:40:48.633784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d0e18f86f7'
down_revision: Union[str, Sequence[str], None] = 'd22e0f4f34be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pubkey_prefix', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_pubkey_prefix'), ['pubkey_prefix'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_pubkey_prefix'))
        batch_op.drop_column('pubkey_prefix')

    # ### end Alembic commands ###
