"""init

Revision ID: d22e0f4f34be
Revises: 
Create Date: 2026-05-18 23:29:11.282334

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd22e0f4f34be'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('psk', sa.String(length=128), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idx')
    )
    op.create_table('contacts',
    sa.Column('pub_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('last_advert', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.PrimaryKeyConstraint('pub_key')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg_type', sa.String(length=4), nullable=False),
    sa.Column('contact_pub_key', sa.String(length=64), nullable=True),
    sa.Column('channel_idx', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column(
        'timestamp',
        sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.Column('ack_state', sa.String(length=16), nullable=False),
    sa.Column('ack_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_ack_hex', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_channel_idx'), ['channel_idx'], unique=False)
        batch_op.create_index('ix_messages_channel_ts', ['channel_idx', 'timestamp'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_messages_contact_pub_key'),
            ['contact_pub_key'],
            unique=False,
        )
        batch_op.create_index(
            'ix_messages_contact_ts',
            ['contact_pub_key', 'timestamp'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_messages_expected_ack_hex'),
            ['expected_ack_hex'],
            unique=False,
        )
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=128), nullable=False),
    sa.Column('auth', sa.String(length=64), nullable=False),
    sa.Column('ua', sa.String(length=255), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', name='uq_push_endpoint')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('push_subscriptions')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_messages_expected_ack_hex'))
        batch_op.drop_index('ix_messages_contact_ts')
        batch_op.drop_index(batch_op.f('ix_messages_contact_pub_key'))
        batch_op.drop_index('ix_messages_channel_ts')
        batch_op.drop_index(batch_op.f('ix_messages_channel_idx'))

    op.drop_table('messages')
    op.drop_table('contacts')
    op.drop_table('channels')
    # ### end Alembic commands ###
